### ISSUE TITLE
What does this need on the server side?

### ISSUE THREAD

**Issue by mercmobily** [ajmas/vue-authenticate#17]
This is probably a very stupid question...
I haven't used oAuth in years, and I am getting back into it as I need to implement authentication in my app generator.
One thing I do know is that there is server-to-server communication involved to exchange access tokens, unless using implicit grant or PKCE.

So... am I missing something? I can't see any server code in the repository... what am I supposed to provide, server-wise?

Thank you and sorry for the noise.

**Comment by ajmas** [comment]
Sorry for the late reply.

No server side needed for the auth handshake. Once you have a suitable token then you pass this to whichever service depends on it. If you are communicating with an API server, then you'll either need to be sure it knows how to validate the Bearer token you are passing or that you have a means to exchange the token for a suitable bearer token for you server.

Out of curiosity, did you work it out?
